# Generated by Django 3.0.1 on 2019-12-30 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20191230_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='createdon',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 16, 4, 49, 141649, tzinfo=utc), editable=False),
        ),
    ]
