# Generated by Django 3.0.1 on 2019-12-30 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_auto_20191230_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='createdon',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
